apiVersion: v1 
kind: Service
metadata:
  name: dusvc
# namespace: orane2a1
spec:
  selector:
    app: oranpod1
  type: NodePort
  ports:
  - port: 4043
    targetPort: 4043
    nodePort: 31522
    protocol: SCTP
  externalIPs:
    - 10.133.35.135
